// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5EGt_vaWHkusW0WDgV7qDM9fYK4ggAg',
    appId: '1:680072344368:web:ed5bc871e101c5ebbbcef5',
    messagingSenderId: '680072344368',
    projectId: 'insta-clone-16e81',
    authDomain: 'insta-clone-16e81.firebaseapp.com',
    storageBucket: 'insta-clone-16e81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASgD8Qi40wZZ3i-oxuJ6Rs412bu_GBbs0',
    appId: '1:680072344368:android:9f41a8d648208c77bbcef5',
    messagingSenderId: '680072344368',
    projectId: 'insta-clone-16e81',
    storageBucket: 'insta-clone-16e81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL69noYWYLUtqyNyYipzZ5mMeWl2yXdZg',
    appId: '1:680072344368:ios:d78beb165715072bbbcef5',
    messagingSenderId: '680072344368',
    projectId: 'insta-clone-16e81',
    storageBucket: 'insta-clone-16e81.appspot.com',
    iosClientId: '680072344368-g6j2tfq781empq2qf5mvg1jhi0ngparb.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL69noYWYLUtqyNyYipzZ5mMeWl2yXdZg',
    appId: '1:680072344368:ios:dbbe0208a5917fc4bbcef5',
    messagingSenderId: '680072344368',
    projectId: 'insta-clone-16e81',
    storageBucket: 'insta-clone-16e81.appspot.com',
    iosClientId: '680072344368-lr8anu5mdcq8ukh0vdhgkt04tv5v413c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone.RunnerTests',
  );
}
